# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: BuildPlatform
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: Docker@2
      inputs:
        containerRegistry: "Docker Hub Service Connection"
        repository: 'rohitrustagi007/platformservice'
        command: buildAndPush
        dockerfile: '$(Build.SourcesDirectory)/PlatformService/Dockerfile'
        tags: |
           $(tag)

- stage: BuildCommand
  displayName: Build Command Service
  jobs:
    - job: Build
      displayName: Build
      pool:
        vmImage: ubuntu-latest
      variables: 
        -group: TerraformEnvVars 
      steps:
      - task: Docker@2
        inputs:
          containerRegistry: "Docker Hub Service Connection"
          repository: 'rohitrustagi007/commandservice'
          command: buildAndPush
          dockerfile: '$(Build.SourcesDirectory)/CommandService/Dockerfile'
          tags: |
            $(tag)
