kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: kube-dash-role-binding
  namespace: default
subjects:
  - kind: User
    name: kube-dash-role-binding
    apiGroup: 'rbac.authorization.k8s.io'
  - kind: ServiceAccount
    name: sourabh
    namespace: kubernetes-dashboard
roleRef:
  kind: ClusterRole
  name: kube-dash-role-binding
  apiGroup: 'rbac.authorization.k8s.io'