apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-nginx-srv
  annotations: 
      kubernetes.io/ingress.class: nginx
      nginx.ingress.kubernetes.io/use-regex: 'true'  
  labels:
    name: myingress  
spec:
  rules:
  - host: acme.com
    http:
      paths:
      - pathType: Prefix
        path: "/api/platforms"
        backend:
          service:
            name: platform-cluster-ip
            port: 
              number: 80
      - pathType: Prefix
        path: "/api/c/platforms/test"
        backend:
          service:
            name: command-cluster-ip
            port: 
              number: 80


