apiVersion: apps/v1
kind: Deployment
metadata:
  name: mssql-depl
  namespace: evolution
spec:
  selector:
    matchLabels:
      app: mssql-server
  template:
    metadata:
      labels:
        app: mssql-server
    spec:
      containers:
      - name: mssql-server
        image: mcr.microsoft.com/mssql/server:2017-latest
        ports:
        - containerPort: 1433
        env:
        - name: MSSQL_PID
          value: "Express"
        - name: ACCEPT_EULA
          value: "Y"
        - name: SA_PASSWORD
          valueFrom: 
            secretKeyRef:
              name: mssql 
              key: SA_PASSWORD
        volumeMounts:
        - mountPath: /var/opt/mssql/data
          name: mssqldb
      volumes:
      - name: mssqldb
        persistentVolumeClaim:
          claimName: sqlserver-pvc

---

apiVersion: v1
kind: Service
metadata:
  name: mssql-cluster-ip
spec:
  type: ClusterIP
  selector:
    app: mssql-server
  ports:
  - name: mssql-server
    protocol: TCP
    port: 1433
    targetPort: 1433

---
apiVersion: v1
kind: Service
metadata:
  name: mssql-loadbalancer
spec:
  type: LoadBalancer
  selector:
    app: mssql-server
  ports:
  - protocol: TCP
    port: 1433
    targetPort: 1433