apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    prometheus: kube-prometheus
    app.kubernetes.io/part-of: kube-prometheus
  name: platform-svc-monitor
  namespace: monitoring 
spec:
  selector:
    matchLabels:
      app: platformservice
  endpoints:
  - port: platformservice


