apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: platform-svc-monitor
  labels:
    team: platform-svc-monitor
spec:
  selector:
    matchLabels:
      app: platformservice
  endpoints:
  - port: platformservice
  namespaceSelector:
    any: true
