apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: platform-monitor
  labels:
    team: platform-service
spec:
  selector:
    matchLabels:
      app: platformservice
  podMetricsEndpoints:
  - targetPort: 80