apiVersion: v1
kind: Namespace
metadata:
  name: kuma-demo
  labels:
    kuma.io/sidecar-injection: enabled

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-k8-mesh-depl
  namespace: kuma-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-k8-mesh
  template:
    metadata:
      labels:
        app: hello-k8-mesh
      annotations:
        kuma.io/mesh: new-mesh  
    spec:
      containers:
      - name: hello-k8-mesh
        image: hello-world
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"

---


apiVersion: v1
kind: Service
metadata:
  name: hello-k8-mesh-cluster-ip
  namespace: kuma-demo
spec:
  type: ClusterIP
  selector:
    app: hello-k8-mesh
  ports:
  - name: hello-k8-mesh
    protocol: TCP
    port: 80
    targetPort: 80