kind: PodMonitor
apiVersion: monitoring.coreos.com/V1
metadata:
  name: mesh-cp
  namespace: monitoring
spec:
  selector: 
    matchLables:
      app: hello-k8-mesh
  namespaceSelector: 
    any: true
  podMetricEndpoints:
    - targetPort: 5670
      path: /metrics 
      scrapeTimeout: 10s