kind: PodMonitor
apiVersion: monitoring.coreos.com/v1
metadata:
  name: mesh-cp
  namespace: monitoring
spec:
  selector: 
    matchLabels:
      app: hello-k8-mesh
  namespaceSelector: 
    any: true
  podMetricsEndpoints:
    - targetPort: 5670
      path: /metrics 
      scrapeTimeout: 10s